#! /bin/sh

setxkbmap -option ctrl:nocaps
setxkbmap -option compose:rctrl-altgr
# to reset the xkbmap: `setxkbmap -option`

xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5

sudo sh -c "echo -n 196 > /sys/devices/platform/i8042/serio1/serio2/sensitivity"
sudo su -c "echo -n 130 > /sys/devices/platform/i8042/serio1/serio2/speed"
